// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.3
// source: proto/ProjectEntryModels.proto

package projectmodels

import (
	commonmodels "github.com/ag-computational-bio/BioDataDBModels/go/commonmodels"
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ProjectUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID string             `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Scope  commonmodels.Scope `protobuf:"varint,2,opt,name=Scope,proto3,enum=Scope" json:"Scope,omitempty"`
}

func (x *ProjectUser) Reset() {
	*x = ProjectUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ProjectEntryModels_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectUser) ProtoMessage() {}

func (x *ProjectUser) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ProjectEntryModels_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectUser.ProtoReflect.Descriptor instead.
func (*ProjectUser) Descriptor() ([]byte, []int) {
	return file_proto_ProjectEntryModels_proto_rawDescGZIP(), []int{0}
}

func (x *ProjectUser) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *ProjectUser) GetScope() commonmodels.Scope {
	if x != nil {
		return x.Scope
	}
	return commonmodels.Scope_Read
}

type Project struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID          string         `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Description string         `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	Users       []*ProjectUser `protobuf:"bytes,3,rep,name=Users,proto3" json:"Users,omitempty"`
	ProjectName string         `protobuf:"bytes,4,opt,name=ProjectName,proto3" json:"ProjectName,omitempty"`
}

func (x *Project) Reset() {
	*x = Project{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ProjectEntryModels_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ProjectEntryModels_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_proto_ProjectEntryModels_proto_rawDescGZIP(), []int{1}
}

func (x *Project) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Project) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Project) GetUsers() []*ProjectUser {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *Project) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

var File_proto_ProjectEntryModels_proto protoreflect.FileDescriptor

var file_proto_ProjectEntryModels_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x43, 0x0a, 0x0b, 0x50, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x55, 0x73, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x12, 0x1c, 0x0a, 0x05, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x06, 0x2e, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x52, 0x05, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x22,
	0x81, 0x01, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x44,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a,
	0x05, 0x55, 0x73, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x50,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x05, 0x55, 0x73, 0x65, 0x72,
	0x73, 0x12, 0x20, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x42, 0x42, 0x5a, 0x40, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x61, 0x67, 0x2d, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x61, 0x6c, 0x2d, 0x62, 0x69, 0x6f, 0x2f, 0x42, 0x69, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x44, 0x42,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_ProjectEntryModels_proto_rawDescOnce sync.Once
	file_proto_ProjectEntryModels_proto_rawDescData = file_proto_ProjectEntryModels_proto_rawDesc
)

func file_proto_ProjectEntryModels_proto_rawDescGZIP() []byte {
	file_proto_ProjectEntryModels_proto_rawDescOnce.Do(func() {
		file_proto_ProjectEntryModels_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_ProjectEntryModels_proto_rawDescData)
	})
	return file_proto_ProjectEntryModels_proto_rawDescData
}

var file_proto_ProjectEntryModels_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_ProjectEntryModels_proto_goTypes = []interface{}{
	(*ProjectUser)(nil),     // 0: ProjectUser
	(*Project)(nil),         // 1: Project
	(commonmodels.Scope)(0), // 2: Scope
}
var file_proto_ProjectEntryModels_proto_depIdxs = []int32{
	2, // 0: ProjectUser.Scope:type_name -> Scope
	0, // 1: Project.Users:type_name -> ProjectUser
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_ProjectEntryModels_proto_init() }
func file_proto_ProjectEntryModels_proto_init() {
	if File_proto_ProjectEntryModels_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_ProjectEntryModels_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ProjectEntryModels_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Project); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_ProjectEntryModels_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_ProjectEntryModels_proto_goTypes,
		DependencyIndexes: file_proto_ProjectEntryModels_proto_depIdxs,
		MessageInfos:      file_proto_ProjectEntryModels_proto_msgTypes,
	}.Build()
	File_proto_ProjectEntryModels_proto = out.File
	file_proto_ProjectEntryModels_proto_rawDesc = nil
	file_proto_ProjectEntryModels_proto_goTypes = nil
	file_proto_ProjectEntryModels_proto_depIdxs = nil
}
