# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/AuthModels.proto

require 'google/protobuf'

require 'proto/CommonModels_pb'
require 'google/protobuf/timestamp_pb'
require 'protoc/gateway/options/annotations_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/AuthModels.proto", :syntax => :proto3) do
    add_message "TokenList" do
      optional :ProjectID, :string, 1
      repeated :token, :message, 2, "TokenEntry"
    end
    add_message "TokenEntry" do
      optional :ID, :string, 1
      optional :UserID, :message, 2, "User"
      optional :Token, :string, 3
      optional :Resource, :enum, 4, "Resource"
      optional :Created, :message, 5, "google.protobuf.Timestamp"
      optional :Expires, :message, 6, "google.protobuf.Timestamp"
    end
    add_message "CreateTokenRequest" do
      optional :ResourceID, :string, 1
      repeated :Rights, :enum, 2, "Right"
      optional :Resource, :enum, 3, "Resource"
      optional :Expires, :message, 4, "google.protobuf.Timestamp"
    end
  end
end

TokenList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TokenList").msgclass
TokenEntry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TokenEntry").msgclass
CreateTokenRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CreateTokenRequest").msgclass
