# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/AuthModels.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'protoc/gateway/options/annotations_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/AuthModels.proto", :syntax => :proto3) do
    add_message "TokenList" do
      optional :UserID, :string, 1
      repeated :token, :message, 2, "TokenEntry"
    end
    add_message "TokenEntry" do
      optional :UserID, :string, 1
      optional :Token, :string, 2
      optional :Created, :message, 3, "google.protobuf.Timestamp"
      optional :Expires, :message, 4, "google.protobuf.Timestamp"
      optional :DatasetID, :string, 5
      repeated :AccessScopes, :enum, 6, "Scope"
    end
    add_message "CreateTokenRequest" do
      optional :DatasetID, :string, 1
      repeated :AccessScopes, :enum, 2, "Scope"
      optional :Expires, :message, 3, "google.protobuf.Timestamp"
    end
    add_enum "Scope" do
      value :Read, 0
      value :Write, 1
    end
  end
end

TokenList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TokenList").msgclass
TokenEntry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TokenEntry").msgclass
CreateTokenRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CreateTokenRequest").msgclass
Scope = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Scope").enummodule
