# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/CommonModels.proto

require 'google/protobuf'

require 'protoc/gateway/options/annotations_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/CommonModels.proto", :syntax => :proto3) do
    add_message "Empty" do
    end
    add_message "Location" do
      optional :Bucket, :string, 1
      optional :Key, :string, 2
      optional :URL, :string, 3
    end
    add_message "Origin" do
      optional :Link, :string, 1
      optional :ObjectStorageLocatio, :message, 2, "Location"
      optional :OriginType, :enum, 4, "Origin.OriginTypeEnum"
    end
    add_enum "Origin.OriginTypeEnum" do
      value :ObjectStorage, 0
      value :OriginLink, 1
    end
    add_message "ID" do
      optional :ID, :string, 1
    end
    add_message "Version" do
      optional :Major, :int32, 1
      optional :Minor, :int32, 2
      optional :Patch, :int32, 3
      optional :Revision, :int32, 4
      optional :Stage, :enum, 5, "Version.VersionStage"
    end
    add_enum "Version.VersionStage" do
      value :Stable, 0
      value :ReleaseCandidate, 1
      value :Beta, 2
      value :Alpha, 3
    end
    add_message "Int64Wrapper" do
      optional :Value, :int64, 1
    end
    add_message "IDList" do
      repeated :IDs, :string, 1
    end
    add_enum "Scope" do
      value :Read, 0
      value :Write, 1
    end
  end
end

Empty = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Empty").msgclass
Location = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Location").msgclass
Origin = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Origin").msgclass
Origin::OriginTypeEnum = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Origin.OriginTypeEnum").enummodule
ID = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ID").msgclass
Version = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Version").msgclass
Version::VersionStage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Version.VersionStage").enummodule
Int64Wrapper = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Int64Wrapper").msgclass
IDList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("IDList").msgclass
Scope = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Scope").enummodule
