# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/DatasetAPI.proto

require 'google/protobuf'

require 'proto/DatasetModels_pb'
require 'proto/DatasetEntryModels_pb'
require 'proto/CommonModels_pb'
require 'google/api/annotations_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/DatasetAPI.proto", :syntax => :proto3) do
  end
end

