# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: proto/DatasetAPI.proto for package ''

require 'grpc'
require 'proto/DatasetAPI_pb'

module DatasetService
  # Dataset management service
  # Manages all dataset related services
  # All data objects are associated with one data dataset
  # Dataset versions group these data objects, which makes them reusable
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'DatasetService'

    # CreateNewDataset Creates a new dataset
    rpc :CreateNewDataset, CreateDatasetRequest, DatasetEntry
    # Datasets Lists all datasets
    rpc :Datasets, ID, DatasetList
    # DeleteDataset Delete a dataset
    rpc :DeleteDataset, ID, Empty
    # Creates a new dataset version based on an existing dataset
    rpc :CreateNewDatasetVersion, NewDatasetVersionRequest, DatasetVersionEntry
    # Lists Versions of a dataset
    rpc :DatasetVersions, ID, DatasetVersionList
    # Deletes a dataset version
    # This should not delete the underlaying dataset objects
    rpc :DeleteDatasetVersion, ID, Empty
    # Updates the expected number of objects in a dataset
    rpc :UpdateDatasetVersionObjectCount, UpdateDatasetVersionObjectCountRequest, Empty
    # Lists all entities of a dataset
    rpc :DatasetVersionObjects, ID, DatasetObjectList
    # Creates preauth download links for all entities of a dataset
    rpc :DatasetVersionObjectsLinks, ID, DatasetObjectLinks
    # DatasetObjectLink A download link for 
    rpc :CreateDatasetObjectLink, ID, DatasetObjectLink
  end

  Stub = Service.rpc_stub_class
end
