# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/DatasetModels.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'google/protobuf/struct_pb'
require 'proto/CommonModels_pb'
require 'protoc/gateway/options/annotations_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/DatasetModels.proto", :syntax => :proto3) do
    add_message "DatasetEntry" do
      optional :ID, :string, 1
      optional :Metadata, :message, 2, "DatasetEntryMetadata"
      optional :CurrentVersion, :string, 3
    end
    add_message "DatasetEntryMetadata" do
      optional :Datasetname, :string, 1
      optional :Datasettype, :string, 2
      optional :OwnerID, :string, 3
      optional :isPublic, :bool, 4
    end
    add_message "DatasetObjectEntry" do
      optional :ID, :string, 1
      optional :Metadata, :message, 3, "DatasetObjectMetaData"
    end
    add_message "DatasetObjectMetaData" do
      optional :Filename, :string, 1
      optional :Filetype, :string, 2
      optional :Name, :string, 3
      optional :Version, :message, 4, "Version"
      optional :Origin, :message, 5, "Origin"
      optional :ContentLen, :int32, 6
      optional :DatasetID, :string, 7
      optional :DatasetVersionID, :string, 8
      optional :Location, :message, 9, "Location"
      optional :AdditionalMetadata, :message, 10, "google.protobuf.Struct"
    end
    add_message "DatasetObjectLinks" do
      optional :ID, :string, 1
      repeated :Entites, :message, 2, "DatasetObjectLink"
    end
    add_message "DatasetObjectLink" do
      optional :Link, :string, 1
      optional :ObjectID, :string, 2
    end
    add_message "CreateDatasetRequest" do
      optional :DatasetName, :string, 1
      optional :Datatype, :string, 2
    end
    add_message "UpdateDatasetVersionObjectCountRequest" do
      optional :DatasetVersionID, :string, 1
      optional :Value, :int64, 2
    end
    add_message "DatasetList" do
      repeated :Datasets, :message, 1, "DatasetEntry"
    end
    add_message "DatasetVersionList" do
      repeated :DatasetVersions, :message, 2, "DatasetVersionEntry"
    end
    add_message "DatasetObjectList" do
      repeated :DatasetVersionObjects, :message, 1, "DatasetObjectEntry"
    end
    add_message "DatasetVersionEntry" do
      optional :ID, :string, 1
      optional :Metadata, :message, 2, "DatasetVersionMetadata"
    end
    add_message "DatasetVersionMetadata" do
      optional :DatasetID, :string, 1
      optional :DatasetName, :string, 2
      optional :Version, :message, 3, "Version"
      optional :Created, :message, 4, "google.protobuf.Timestamp"
      optional :AdditionalMetadata, :message, 5, "google.protobuf.Struct"
      optional :AdditionalMetadataMessageRef, :string, 6
      optional :AdditionalObjectMetadataMessageRef, :string, 7
      optional :ObjectCount, :int64, 8
      optional :ObjectLinkCount, :int64, 9
      optional :ExpectedObjectCount, :int64, 10
      optional :Status, :enum, 11, "DatasetVersionMetadata.DatasetVersionStatus"
    end
    add_enum "DatasetVersionMetadata.DatasetVersionStatus" do
      value :InitialUploading, 0
      value :Finished, 1
      value :AdditionalUploading, 2
      value :Deleting, 3
    end
    add_message "NewDatasetVersionRequest" do
      optional :DatasetID, :string, 1
      optional :Version, :message, 2, "Version"
      optional :AdditionalMetadataMessageRef, :string, 3
      optional :AdditionalObjectMetadataMessageRef, :string, 4
      optional :AdditionalMetadata, :message, 5, "google.protobuf.Struct"
      optional :ExpectedObjectCount, :int64, 6
    end
  end
end

DatasetEntry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DatasetEntry").msgclass
DatasetEntryMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DatasetEntryMetadata").msgclass
DatasetObjectEntry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DatasetObjectEntry").msgclass
DatasetObjectMetaData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DatasetObjectMetaData").msgclass
DatasetObjectLinks = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DatasetObjectLinks").msgclass
DatasetObjectLink = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DatasetObjectLink").msgclass
CreateDatasetRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CreateDatasetRequest").msgclass
UpdateDatasetVersionObjectCountRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("UpdateDatasetVersionObjectCountRequest").msgclass
DatasetList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DatasetList").msgclass
DatasetVersionList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DatasetVersionList").msgclass
DatasetObjectList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DatasetObjectList").msgclass
DatasetVersionEntry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DatasetVersionEntry").msgclass
DatasetVersionMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DatasetVersionMetadata").msgclass
DatasetVersionMetadata::DatasetVersionStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DatasetVersionMetadata.DatasetVersionStatus").enummodule
NewDatasetVersionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("NewDatasetVersionRequest").msgclass
