# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/DatasetEntryModels.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'google/protobuf/struct_pb'
require 'proto/CommonModels_pb'
require 'protoc/gateway/options/annotations_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/DatasetEntryModels.proto", :syntax => :proto3) do
    add_message "DatasetEntry" do
      optional :ID, :string, 1
      optional :Datasetname, :string, 2
      optional :Datasettype, :string, 3
      optional :IsPublic, :bool, 4
      optional :Created, :message, 5, "google.protobuf.Timestamp"
      optional :CurrentVersion, :string, 6
      optional :Status, :enum, 7, "Status"
      optional :OwnerProjectID, :string, 8
      repeated :BurrowedProjectIDs, :string, 9
    end
    add_message "DatasetVersionEntry" do
      optional :ID, :string, 1
      optional :DatasetID, :string, 2
      optional :Datasetname, :string, 3
      optional :Version, :message, 4, "Version"
      optional :Created, :message, 5, "google.protobuf.Timestamp"
      optional :AdditionalMetadata, :message, 56, "google.protobuf.Struct"
      optional :AdditionalMetadataMessageRef, :string, 7
      optional :AdditionalObjectMetadataMessageRef, :string, 8
      optional :ObjectCount, :int64, 9
      optional :ObjectLinkCount, :int64, 10
      optional :ExpectedObjectCount, :int64, 11
      optional :Status, :enum, 12, "Status"
    end
    add_message "DatasetObjectEntry" do
      optional :ID, :string, 1
      optional :Filename, :string, 2
      optional :Filetype, :string, 3
      optional :Name, :string, 4
      optional :Version, :message, 5, "Version"
      optional :Origin, :message, 6, "Origin"
      optional :ContentLen, :int64, 7
      optional :DatasetID, :string, 8
      repeated :DatasetVersionID, :string, 9
      optional :Location, :message, 10, "Location"
      optional :Created, :message, 11, "google.protobuf.Timestamp"
      optional :AdditionalMetadata, :message, 12, "google.protobuf.Struct"
    end
    add_enum "Status" do
      value :Initiating, 0
      value :Available, 1
      value :Updating, 2
      value :Archived, 3
      value :Deleting, 4
    end
  end
end

DatasetEntry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DatasetEntry").msgclass
DatasetVersionEntry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DatasetVersionEntry").msgclass
DatasetObjectEntry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DatasetObjectEntry").msgclass
Status = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Status").enummodule
