# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/LoadAPI.proto

require 'google/protobuf'

require 'proto/LoadModels_pb'
require 'google/api/annotations_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/LoadAPI.proto", :syntax => :proto3) do
  end
end

