# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/LoadModels.proto

require 'google/protobuf'

require 'proto/DatasetEntryModels_pb'
require 'protoc/gateway/options/annotations_pb'
require 'google/protobuf/timestamp_pb'
require 'google/protobuf/struct_pb'
require 'proto/CommonModels_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/LoadModels.proto", :syntax => :proto3) do
    add_message "CreateUploadLinkRequest" do
      optional :DatasetVersionID, :string, 1
      optional :Filename, :string, 2
      optional :Filetype, :string, 3
      optional :Name, :string, 4
      optional :Version, :message, 5, "Version"
      optional :Origin, :message, 6, "Origin"
      optional :ContentLen, :int64, 7
      optional :Location, :message, 10, "Location"
      optional :Created, :message, 11, "google.protobuf.Timestamp"
      optional :AdditionalMetadata, :message, 12, "google.protobuf.Struct"
    end
    add_message "CreateUploadLinkResponse" do
      optional :ID, :string, 1
      optional :Link, :string, 2
      optional :Object, :message, 3, "DatasetObjectEntry"
    end
    add_message "InitMultipartUploadRequest" do
      optional :DatasetVersionID, :string, 1
      optional :Filename, :string, 2
      optional :Filetype, :string, 3
      optional :Name, :string, 4
      optional :Version, :message, 5, "Version"
      optional :Origin, :message, 6, "Origin"
      optional :ContentLen, :int64, 7
      optional :Location, :message, 10, "Location"
      optional :Created, :message, 11, "google.protobuf.Timestamp"
      optional :AdditionalMetadata, :message, 12, "google.protobuf.Struct"
    end
    add_message "InitMultiPartUploadResponse" do
      optional :DatasetObjectID, :string, 1
    end
    add_message "GetMultipartUploadLinkPartRequest" do
      optional :DatasetObjectID, :string, 1
      optional :UploadPart, :int64, 2
      optional :ContentLen, :int64, 3
    end
    add_message "GetMultipartUploadLinkPartResponse" do
      optional :UploadLink, :string, 1
      optional :Etag, :string, 2
    end
    add_message "FinishMultipartUploadRequest" do
      optional :DatasetObjectID, :string, 1
      repeated :CompletedUploadParts, :message, 2, "CompletedUploadParts"
    end
    add_message "CompletedUploadParts" do
      optional :Etag, :string, 1
      optional :Partnumber, :int64, 2
    end
  end
end

CreateUploadLinkRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CreateUploadLinkRequest").msgclass
CreateUploadLinkResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CreateUploadLinkResponse").msgclass
InitMultipartUploadRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("InitMultipartUploadRequest").msgclass
InitMultiPartUploadResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("InitMultiPartUploadResponse").msgclass
GetMultipartUploadLinkPartRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetMultipartUploadLinkPartRequest").msgclass
GetMultipartUploadLinkPartResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetMultipartUploadLinkPartResponse").msgclass
FinishMultipartUploadRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("FinishMultipartUploadRequest").msgclass
CompletedUploadParts = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CompletedUploadParts").msgclass
