# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: proto/MetadataAPI.proto for package ''

require 'grpc'
require 'proto/MetadataAPI_pb'

module MetadataCompositeStore
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'MetadataCompositeStore'

    rpc :InitMetadataDB, InitMetadataDBRequest, MetadataDBEntry
    rpc :ListMetadataDBs, Empty, MetadataDBList
    rpc :InitMetadataDBCollection, InitMetadataCollectionRequest, MetadataDBEntry
    rpc :ListMetadataDBCollections, Empty, MetadataDBCollectionList
    rpc :InsertMetadata, InsertMetadataRequest, Empty
    rpc :AddMetadataIndex, AddMetadataIndexRequest, Empty
    rpc :Query, QueryRequest, Field
  end

  Stub = Service.rpc_stub_class
end
