# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/MetadataAPI.proto

require 'google/protobuf'

require 'proto/MetadataModels_pb'
require 'proto/CommonModels_pb'
require 'google/api/annotations_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/MetadataAPI.proto", :syntax => :proto3) do
  end
end

