# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/ProjectEntryModels.proto

require 'google/protobuf'

require 'proto/CommonModels_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/ProjectEntryModels.proto", :syntax => :proto3) do
    add_message "ProjectEntry" do
      optional :ID, :string, 1
      optional :Description, :string, 2
      repeated :Users, :message, 3, "User"
      optional :ProjectName, :string, 4
    end
  end
end

ProjectEntry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ProjectEntry").msgclass
