// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.4
// source: proto/LoadModels.proto

package loadmodels

import (
	commonmodels "github.com/ag-computational-bio/BioDataDBModels/go/commonmodels"
	datasetapimodels "github.com/ag-computational-bio/BioDataDBModels/go/datasetapimodels"
	datasetentrymodels "github.com/ag-computational-bio/BioDataDBModels/go/datasetentrymodels"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CreateUploadLinkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DatsetObjectGroupID        string                                       `protobuf:"bytes,1,opt,name=DatsetObjectGroupID,proto3" json:"DatsetObjectGroupID,omitempty"`
	CreateDatasetObjectRequest *datasetapimodels.CreateDatasetObjectRequest `protobuf:"bytes,2,opt,name=CreateDatasetObjectRequest,proto3" json:"CreateDatasetObjectRequest,omitempty"`
}

func (x *CreateUploadLinkRequest) Reset() {
	*x = CreateUploadLinkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_LoadModels_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUploadLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUploadLinkRequest) ProtoMessage() {}

func (x *CreateUploadLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_LoadModels_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUploadLinkRequest.ProtoReflect.Descriptor instead.
func (*CreateUploadLinkRequest) Descriptor() ([]byte, []int) {
	return file_proto_LoadModels_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUploadLinkRequest) GetDatsetObjectGroupID() string {
	if x != nil {
		return x.DatsetObjectGroupID
	}
	return ""
}

func (x *CreateUploadLinkRequest) GetCreateDatasetObjectRequest() *datasetapimodels.CreateDatasetObjectRequest {
	if x != nil {
		return x.CreateDatasetObjectRequest
	}
	return nil
}

type CreateUploadLinkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID     string                                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`     // ID of the upload request
	Link   string                                 `protobuf:"bytes,2,opt,name=Link,proto3" json:"Link,omitempty"` // Upload link (normally a presigned put URL for S3)
	Object *datasetentrymodels.DatasetObjectEntry `protobuf:"bytes,3,opt,name=Object,proto3" json:"Object,omitempty"`
}

func (x *CreateUploadLinkResponse) Reset() {
	*x = CreateUploadLinkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_LoadModels_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUploadLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUploadLinkResponse) ProtoMessage() {}

func (x *CreateUploadLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_LoadModels_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUploadLinkResponse.ProtoReflect.Descriptor instead.
func (*CreateUploadLinkResponse) Descriptor() ([]byte, []int) {
	return file_proto_LoadModels_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUploadLinkResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *CreateUploadLinkResponse) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *CreateUploadLinkResponse) GetObject() *datasetentrymodels.DatasetObjectEntry {
	if x != nil {
		return x.Object
	}
	return nil
}

type InitMultipartUploadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DatsetObjectGroupID        string                                       `protobuf:"bytes,1,opt,name=DatsetObjectGroupID,proto3" json:"DatsetObjectGroupID,omitempty"`
	CreateDatasetObjectRequest *datasetapimodels.CreateDatasetObjectRequest `protobuf:"bytes,2,opt,name=CreateDatasetObjectRequest,proto3" json:"CreateDatasetObjectRequest,omitempty"`
}

func (x *InitMultipartUploadRequest) Reset() {
	*x = InitMultipartUploadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_LoadModels_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitMultipartUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitMultipartUploadRequest) ProtoMessage() {}

func (x *InitMultipartUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_LoadModels_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitMultipartUploadRequest.ProtoReflect.Descriptor instead.
func (*InitMultipartUploadRequest) Descriptor() ([]byte, []int) {
	return file_proto_LoadModels_proto_rawDescGZIP(), []int{2}
}

func (x *InitMultipartUploadRequest) GetDatsetObjectGroupID() string {
	if x != nil {
		return x.DatsetObjectGroupID
	}
	return ""
}

func (x *InitMultipartUploadRequest) GetCreateDatasetObjectRequest() *datasetapimodels.CreateDatasetObjectRequest {
	if x != nil {
		return x.CreateDatasetObjectRequest
	}
	return nil
}

type GetMultipartUploadLinkPartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DatasetObjectID string `protobuf:"bytes,1,opt,name=DatasetObjectID,proto3" json:"DatasetObjectID,omitempty"`
	UploadPart      int64  `protobuf:"varint,2,opt,name=UploadPart,proto3" json:"UploadPart,omitempty"`
	ContentLen      int64  `protobuf:"varint,3,opt,name=ContentLen,proto3" json:"ContentLen,omitempty"`
}

func (x *GetMultipartUploadLinkPartRequest) Reset() {
	*x = GetMultipartUploadLinkPartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_LoadModels_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMultipartUploadLinkPartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMultipartUploadLinkPartRequest) ProtoMessage() {}

func (x *GetMultipartUploadLinkPartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_LoadModels_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMultipartUploadLinkPartRequest.ProtoReflect.Descriptor instead.
func (*GetMultipartUploadLinkPartRequest) Descriptor() ([]byte, []int) {
	return file_proto_LoadModels_proto_rawDescGZIP(), []int{3}
}

func (x *GetMultipartUploadLinkPartRequest) GetDatasetObjectID() string {
	if x != nil {
		return x.DatasetObjectID
	}
	return ""
}

func (x *GetMultipartUploadLinkPartRequest) GetUploadPart() int64 {
	if x != nil {
		return x.UploadPart
	}
	return 0
}

func (x *GetMultipartUploadLinkPartRequest) GetContentLen() int64 {
	if x != nil {
		return x.ContentLen
	}
	return 0
}

type GetMultipartUploadLinkPartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UploadLink string `protobuf:"bytes,1,opt,name=UploadLink,proto3" json:"UploadLink,omitempty"`
	Etag       string `protobuf:"bytes,2,opt,name=Etag,proto3" json:"Etag,omitempty"`
}

func (x *GetMultipartUploadLinkPartResponse) Reset() {
	*x = GetMultipartUploadLinkPartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_LoadModels_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMultipartUploadLinkPartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMultipartUploadLinkPartResponse) ProtoMessage() {}

func (x *GetMultipartUploadLinkPartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_LoadModels_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMultipartUploadLinkPartResponse.ProtoReflect.Descriptor instead.
func (*GetMultipartUploadLinkPartResponse) Descriptor() ([]byte, []int) {
	return file_proto_LoadModels_proto_rawDescGZIP(), []int{4}
}

func (x *GetMultipartUploadLinkPartResponse) GetUploadLink() string {
	if x != nil {
		return x.UploadLink
	}
	return ""
}

func (x *GetMultipartUploadLinkPartResponse) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

type FinishMultipartUploadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DatasetObjectID      string                  `protobuf:"bytes,1,opt,name=DatasetObjectID,proto3" json:"DatasetObjectID,omitempty"`
	CompletedUploadParts []*CompletedUploadParts `protobuf:"bytes,2,rep,name=CompletedUploadParts,proto3" json:"CompletedUploadParts,omitempty"`
}

func (x *FinishMultipartUploadRequest) Reset() {
	*x = FinishMultipartUploadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_LoadModels_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinishMultipartUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishMultipartUploadRequest) ProtoMessage() {}

func (x *FinishMultipartUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_LoadModels_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishMultipartUploadRequest.ProtoReflect.Descriptor instead.
func (*FinishMultipartUploadRequest) Descriptor() ([]byte, []int) {
	return file_proto_LoadModels_proto_rawDescGZIP(), []int{5}
}

func (x *FinishMultipartUploadRequest) GetDatasetObjectID() string {
	if x != nil {
		return x.DatasetObjectID
	}
	return ""
}

func (x *FinishMultipartUploadRequest) GetCompletedUploadParts() []*CompletedUploadParts {
	if x != nil {
		return x.CompletedUploadParts
	}
	return nil
}

type GetDownloadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resource []*ResourceRequest `protobuf:"bytes,1,rep,name=Resource,proto3" json:"Resource,omitempty"`
}

func (x *GetDownloadRequest) Reset() {
	*x = GetDownloadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_LoadModels_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadRequest) ProtoMessage() {}

func (x *GetDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_LoadModels_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadRequest.ProtoReflect.Descriptor instead.
func (*GetDownloadRequest) Descriptor() ([]byte, []int) {
	return file_proto_LoadModels_proto_rawDescGZIP(), []int{6}
}

func (x *GetDownloadRequest) GetResource() []*ResourceRequest {
	if x != nil {
		return x.Resource
	}
	return nil
}

type ResourceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resource   commonmodels.Resource `protobuf:"varint,1,opt,name=Resource,proto3,enum=Resource" json:"Resource,omitempty"`
	ResourceID string                `protobuf:"bytes,2,opt,name=ResourceID,proto3" json:"ResourceID,omitempty"`
}

func (x *ResourceRequest) Reset() {
	*x = ResourceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_LoadModels_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRequest) ProtoMessage() {}

func (x *ResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_LoadModels_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRequest.ProtoReflect.Descriptor instead.
func (*ResourceRequest) Descriptor() ([]byte, []int) {
	return file_proto_LoadModels_proto_rawDescGZIP(), []int{7}
}

func (x *ResourceRequest) GetResource() commonmodels.Resource {
	if x != nil {
		return x.Resource
	}
	return commonmodels.Resource_Project
}

func (x *ResourceRequest) GetResourceID() string {
	if x != nil {
		return x.ResourceID
	}
	return ""
}

type GetDownloadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Links []*ObjectDownloadLink `protobuf:"bytes,1,rep,name=Links,proto3" json:"Links,omitempty"`
}

func (x *GetDownloadResponse) Reset() {
	*x = GetDownloadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_LoadModels_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadResponse) ProtoMessage() {}

func (x *GetDownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_LoadModels_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadResponse.ProtoReflect.Descriptor instead.
func (*GetDownloadResponse) Descriptor() ([]byte, []int) {
	return file_proto_LoadModels_proto_rawDescGZIP(), []int{8}
}

func (x *GetDownloadResponse) GetLinks() []*ObjectDownloadLink {
	if x != nil {
		return x.Links
	}
	return nil
}

type ObjectDownloadLink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Link   string                                 `protobuf:"bytes,1,opt,name=Link,proto3" json:"Link,omitempty"`
	Object *datasetentrymodels.DatasetObjectEntry `protobuf:"bytes,2,opt,name=Object,proto3" json:"Object,omitempty"`
}

func (x *ObjectDownloadLink) Reset() {
	*x = ObjectDownloadLink{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_LoadModels_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectDownloadLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectDownloadLink) ProtoMessage() {}

func (x *ObjectDownloadLink) ProtoReflect() protoreflect.Message {
	mi := &file_proto_LoadModels_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectDownloadLink.ProtoReflect.Descriptor instead.
func (*ObjectDownloadLink) Descriptor() ([]byte, []int) {
	return file_proto_LoadModels_proto_rawDescGZIP(), []int{9}
}

func (x *ObjectDownloadLink) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *ObjectDownloadLink) GetObject() *datasetentrymodels.DatasetObjectEntry {
	if x != nil {
		return x.Object
	}
	return nil
}

type CompletedUploadParts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Etag       string `protobuf:"bytes,1,opt,name=Etag,proto3" json:"Etag,omitempty"`
	Partnumber int64  `protobuf:"varint,2,opt,name=Partnumber,proto3" json:"Partnumber,omitempty"`
}

func (x *CompletedUploadParts) Reset() {
	*x = CompletedUploadParts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_LoadModels_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompletedUploadParts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletedUploadParts) ProtoMessage() {}

func (x *CompletedUploadParts) ProtoReflect() protoreflect.Message {
	mi := &file_proto_LoadModels_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletedUploadParts.ProtoReflect.Descriptor instead.
func (*CompletedUploadParts) Descriptor() ([]byte, []int) {
	return file_proto_LoadModels_proto_rawDescGZIP(), []int{10}
}

func (x *CompletedUploadParts) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *CompletedUploadParts) GetPartnumber() int64 {
	if x != nil {
		return x.Partnumber
	}
	return 0
}

var File_proto_LoadModels_proto protoreflect.FileDescriptor

var file_proto_LoadModels_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x4c, 0x6f, 0x61, 0x64, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x44, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x44, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x41, 0x50, 0x49, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x28, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2f, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x61,
	0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa8, 0x01, 0x0a, 0x17, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x13, 0x44, 0x61, 0x74, 0x73, 0x65, 0x74,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x13, 0x44, 0x61, 0x74, 0x73, 0x65, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x12, 0x5b, 0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x1a, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xaf, 0x01, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x4c, 0x69, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x2b, 0x0a, 0x06, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x3a, 0x42, 0x92, 0x41, 0x3f, 0x0a, 0x3d, 0x2a, 0x0a, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x32, 0x2f, 0x41, 0x20, 0x70, 0x72, 0x65, 0x73, 0x69, 0x67,
	0x6e, 0x65, 0x64, 0x20, 0x55, 0x52, 0x4c, 0x20, 0x6c, 0x69, 0x6e, 0x6b, 0x20, 0x61, 0x6e, 0x64,
	0x20, 0x69, 0x74, 0x73, 0x20, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x20, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x20, 0x55, 0x52, 0x4c, 0x22, 0xab, 0x01, 0x0a, 0x1a, 0x49, 0x6e, 0x69, 0x74,
	0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x61, 0x72, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x13, 0x44, 0x61, 0x74, 0x73, 0x65, 0x74,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x13, 0x44, 0x61, 0x74, 0x73, 0x65, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x12, 0x5b, 0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x1a, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x8d, 0x01, 0x0a, 0x21, 0x47, 0x65, 0x74, 0x4d, 0x75, 0x6c,
	0x74, 0x69, 0x70, 0x61, 0x72, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4c, 0x69, 0x6e, 0x6b,
	0x50, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x44,
	0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x44, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x50,
	0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x50, 0x61, 0x72, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x4c, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x4c, 0x65, 0x6e, 0x22, 0x58, 0x0a, 0x22, 0x47, 0x65, 0x74, 0x4d, 0x75, 0x6c, 0x74,
	0x69, 0x70, 0x61, 0x72, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x50,
	0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x45,
	0x74, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x45, 0x74, 0x61, 0x67, 0x22,
	0x93, 0x01, 0x0a, 0x1c, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70,
	0x61, 0x72, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x28, 0x0a, 0x0f, 0x44, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x44, 0x61, 0x74, 0x61, 0x73,
	0x65, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x44, 0x12, 0x49, 0x0a, 0x14, 0x43, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x61, 0x72,
	0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x65, 0x64, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x61, 0x72, 0x74, 0x73, 0x52,
	0x14, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x50, 0x61, 0x72, 0x74, 0x73, 0x22, 0x42, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x77, 0x6e,
	0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x08, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52,
	0x08, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x58, 0x0a, 0x0f, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x08,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09,
	0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x08, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x49, 0x44, 0x22, 0x40, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f,
	0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x05, 0x4c, 0x69,
	0x6e, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x05,
	0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x22, 0x55, 0x0a, 0x12, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x44,
	0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x4c,
	0x69, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4c, 0x69, 0x6e, 0x6b, 0x12,
	0x2b, 0x0a, 0x06, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x4a, 0x0a, 0x14,
	0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x50,
	0x61, 0x72, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x45, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x45, 0x74, 0x61, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x61, 0x72, 0x74,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x50, 0x61,
	0x72, 0x74, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x42, 0x3f, 0x5a, 0x3d, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x67, 0x2d, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x2d, 0x62, 0x69, 0x6f, 0x2f, 0x42, 0x69, 0x6f, 0x44,
	0x61, 0x74, 0x61, 0x44, 0x42, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x67, 0x6f, 0x2f, 0x6c,
	0x6f, 0x61, 0x64, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_LoadModels_proto_rawDescOnce sync.Once
	file_proto_LoadModels_proto_rawDescData = file_proto_LoadModels_proto_rawDesc
)

func file_proto_LoadModels_proto_rawDescGZIP() []byte {
	file_proto_LoadModels_proto_rawDescOnce.Do(func() {
		file_proto_LoadModels_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_LoadModels_proto_rawDescData)
	})
	return file_proto_LoadModels_proto_rawDescData
}

var file_proto_LoadModels_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_LoadModels_proto_goTypes = []interface{}{
	(*CreateUploadLinkRequest)(nil),                     // 0: CreateUploadLinkRequest
	(*CreateUploadLinkResponse)(nil),                    // 1: CreateUploadLinkResponse
	(*InitMultipartUploadRequest)(nil),                  // 2: InitMultipartUploadRequest
	(*GetMultipartUploadLinkPartRequest)(nil),           // 3: GetMultipartUploadLinkPartRequest
	(*GetMultipartUploadLinkPartResponse)(nil),          // 4: GetMultipartUploadLinkPartResponse
	(*FinishMultipartUploadRequest)(nil),                // 5: FinishMultipartUploadRequest
	(*GetDownloadRequest)(nil),                          // 6: GetDownloadRequest
	(*ResourceRequest)(nil),                             // 7: ResourceRequest
	(*GetDownloadResponse)(nil),                         // 8: GetDownloadResponse
	(*ObjectDownloadLink)(nil),                          // 9: ObjectDownloadLink
	(*CompletedUploadParts)(nil),                        // 10: CompletedUploadParts
	(*datasetapimodels.CreateDatasetObjectRequest)(nil), // 11: CreateDatasetObjectRequest
	(*datasetentrymodels.DatasetObjectEntry)(nil),       // 12: DatasetObjectEntry
	(commonmodels.Resource)(0),                          // 13: Resource
}
var file_proto_LoadModels_proto_depIdxs = []int32{
	11, // 0: CreateUploadLinkRequest.CreateDatasetObjectRequest:type_name -> CreateDatasetObjectRequest
	12, // 1: CreateUploadLinkResponse.Object:type_name -> DatasetObjectEntry
	11, // 2: InitMultipartUploadRequest.CreateDatasetObjectRequest:type_name -> CreateDatasetObjectRequest
	10, // 3: FinishMultipartUploadRequest.CompletedUploadParts:type_name -> CompletedUploadParts
	7,  // 4: GetDownloadRequest.Resource:type_name -> ResourceRequest
	13, // 5: ResourceRequest.Resource:type_name -> Resource
	9,  // 6: GetDownloadResponse.Links:type_name -> ObjectDownloadLink
	12, // 7: ObjectDownloadLink.Object:type_name -> DatasetObjectEntry
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_LoadModels_proto_init() }
func file_proto_LoadModels_proto_init() {
	if File_proto_LoadModels_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_LoadModels_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUploadLinkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_LoadModels_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUploadLinkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_LoadModels_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitMultipartUploadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_LoadModels_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMultipartUploadLinkPartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_LoadModels_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMultipartUploadLinkPartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_LoadModels_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinishMultipartUploadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_LoadModels_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDownloadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_LoadModels_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_LoadModels_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDownloadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_LoadModels_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectDownloadLink); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_LoadModels_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompletedUploadParts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_LoadModels_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_LoadModels_proto_goTypes,
		DependencyIndexes: file_proto_LoadModels_proto_depIdxs,
		MessageInfos:      file_proto_LoadModels_proto_msgTypes,
	}.Build()
	File_proto_LoadModels_proto = out.File
	file_proto_LoadModels_proto_rawDesc = nil
	file_proto_LoadModels_proto_goTypes = nil
	file_proto_LoadModels_proto_depIdxs = nil
}
